export var MACOS_SYSTEM_COMMANDS = {
  codesign: "/usr/bin/codesign",
  ditto: "/usr/bin/ditto",
  lsof: "/usr/sbin/lsof",
  mdfind: "/usr/bin/mdfind",
  open: "/usr/bin/open",
  osascript: "/usr/bin/osascript",
  pbcopy: "/usr/bin/pbcopy",
  pbpaste: "/usr/bin/pbpaste",
  pgrep: "/usr/bin/pgrep",
  plist: "/usr/bin/plutil",
  plistBuddy: "/usr/libexec/PlistBuddy",
  ps: "/bin/ps",
  screencapture: "/usr/sbin/screencapture",
  sh: "/bin/sh",
  spctl: "/usr/sbin/spctl",
  syspolicyCheck: "/usr/bin/syspolicy_check",
  unzip: "/usr/bin/unzip",
  xattr: "/usr/bin/xattr",
};
